### Numerical Solution Using NumPy

In [1]:
import numpy as np
A = np.array([[1,2],[2,4],[3,1]])
B = np.array([1,3,1])
x = np.random.rand(2)
C = np.dot(A,x)

In [2]:
def f(x):
    C = A*x
    return (np.linalg.norm(np.dot(A,x)-B))**2

In [3]:
f(x)

1.098955793987194

In [4]:
def grad(x):
    C = A*x
    return 2*np.dot(A.T,(np.dot(A,x)-B))

In [5]:
grad(x)

array([4.77912047, 8.62574259])

In [6]:
def gD(x):
    for i in range(10000):
        x = x - 0.01*(grad(x))
        if i%1000 == 0:
            print(f"Iteration : {i} Value of f(x) = {f(x)}")
        ans = x
    print(f"Iteration : {i} = Min value of f = {f(x)} at x = {x}")
    return ans

In [7]:
answer = gD(x)

Iteration : 0 Value of f(x) = 0.42192572469689277
Iteration : 1000 Value of f(x) = 0.19999999999999998
Iteration : 2000 Value of f(x) = 0.19999999999999998
Iteration : 3000 Value of f(x) = 0.19999999999999998
Iteration : 4000 Value of f(x) = 0.19999999999999998
Iteration : 5000 Value of f(x) = 0.19999999999999998
Iteration : 6000 Value of f(x) = 0.19999999999999998
Iteration : 7000 Value of f(x) = 0.19999999999999998
Iteration : 8000 Value of f(x) = 0.19999999999999998
Iteration : 9000 Value of f(x) = 0.19999999999999998
Iteration : 9999 = Min value of f = 0.19999999999999998 at x = [0.12 0.64]


In [8]:
np.linalg.norm(np.dot(A,answer)-B)**2

0.19999999999999998

In [9]:
2*np.dot(A.T,A)

array([[28, 26],
       [26, 42]])

In [10]:
np.dot(A.T,B)

array([10, 15])

In [11]:
np.dot(A.T,A)

array([[14, 13],
       [13, 21]])

In [12]:
np.linalg.norm(np.dot(A,answer)-B)**2

0.19999999999999998