### Numerical Solution using NumPy

In [1]:
import numpy as np
A = np.array([[1,2,1],[2,4,2],[3,1,9],[4,1,0],[2,1,4]])
B = np.array([1,3,1,0,9])
x = np.random.rand(3)

In [2]:
def f(x):
    return (np.linalg.norm(np.dot(A,x)-B))**2

In [3]:
def grad(x):
    return 2*np.dot(A.T,(np.dot(A,x)-B))

## Given learning rate is very high

In [4]:
lr = 0.002 
num_iter = 10000

In [5]:
def gD(x):
    for i in range(num_iter):
        x = x - lr*(grad(x))
        if i%1000 == 0:
            print(f"Iteration : {i} Value of f(x) = {f(x)}")
    answer = x
    print(f"Iteration : {i} = Min value of f = {f(x)} at x = {x}")
    return answer

In [6]:
answer = gD(x)
answer

Iteration : 0 Value of f(x) = 76.87868204873901
Iteration : 1000 Value of f(x) = 56.990482782488314
Iteration : 2000 Value of f(x) = 56.99048278248833
Iteration : 3000 Value of f(x) = 56.99048278248833
Iteration : 4000 Value of f(x) = 56.99048278248833
Iteration : 5000 Value of f(x) = 56.99048278248833
Iteration : 6000 Value of f(x) = 56.99048278248833
Iteration : 7000 Value of f(x) = 56.99048278248833
Iteration : 8000 Value of f(x) = 56.99048278248833
Iteration : 9000 Value of f(x) = 56.99048278248833
Iteration : 9999 = Min value of f = 56.99048278248833 at x = [0.05744939 0.65686105 0.33915902]


array([0.05744939, 0.65686105, 0.33915902])

In [7]:
np.dot(A.T,A)

array([[ 34,  19,  40],
       [ 19,  23,  23],
       [ 40,  23, 102]])

In [8]:
np.dot(A.T,B)

array([28, 24, 52])

In [9]:
np.linalg.norm(np.dot(A,answer)-B)**2

56.99048278248833